### ISSUE TITLE
Error downloading album

### ISSUE THREAD

**Issue by EarlSven** [defvs/monsterutilities#27]
I've downloaded Uncaged Vol 11 and at the end of the download I get this error:

![image](https://user-images.githubusercontent.com/14951410/156083380-b582b43a-c83c-4765-9b96-fca8cc6cc665.png)

Running on Manjaro Linux with OpenJDK JRE 8.

All 85 tracks seem to have downloaded OK though, but the folder still has .part on the end of the name.

**Comment by defvs** [comment]
Hi, thanks for your bug report. I'll be looking into it.

**Comment by proferabg** [comment]
If this helps this is the error
```
java.lang.IllegalStateException: entity.contentType must not be null
	at xerus.monstercat.downloader.ReleaseDownload.download(Download.kt:139)
	at xerus.monstercat.downloader.Download.call(Download.kt:56)
	at xerus.monstercat.downloader.Download.call(Download.kt:39)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Possibly related to #28

**Comment by defvs** [comment]
Fixed, will be released on next update.
